name: pygl_setup
description: Installs GardenLinux Python library

inputs:
  version:
    description: GardenLinux Python library version to install
    default: "0.10.5"
  python_version:
    description: Python version to setup
    default: "3.14"

outputs:
  version:
    description: GardenLinux Python library version
    value: ${{ inputs.version }}
  python_version:
    description: Python version to setup
    value: ${{ inputs.python_version }}

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Restore python site-packages from cache
      id: restore-python-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.local/lib/python${{ inputs.python_version }}/site-packages
        key: pygl-${{ inputs.python_version }}-${{ inputs.version }}

    - name: Install GardenLinux Python library
      shell: bash
      run: |
        pip install --user \
          https://github.com/gardenlinux/python-gardenlinux-lib/releases/download/${{ inputs.version }}/gardenlinux-${{ inputs.version }}-py3-none-any.whl

    - name: Debug
      shell: bash
      run: |
        ls -l ~/.local/bin
        echo $PATH

    - name: Cache python site-packages
      id: save-python-cache
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.local/lib/python${{ inputs.python_version }}/site-packages
        key: pygl-${{ inputs.python_version }}-${{ inputs.version }}
