name: python_lib
description: Installs the given GardenLinux Python library

inputs:
  version:
    description: GardenLinux Python library version
    default: "0.10.5"
  python_version:
    description: Python version to setup
    default: "3.14"

outputs:
  version:
    description: GardenLinux Python library version
    value: ${{ inputs.version }}
  python_version:
    description: Python version to setup
    value: ${{ inputs.python_version }}

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install GardenLinux Python library
      shell: bash
      run: |
        pip install https://github.com/gardenlinux/python-gardenlinux-lib/releases/download/${{ inputs.version }}/gardenlinux-${{ inputs.version }}-py3-none-any.whl
