name: Build
on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "**/README.md"
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
      - uses: ./.github/actions/setup
      - name: Simple poetry build no package
        run: make build
