name: pytests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.13", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2

      - name: Setup Gardenlinux
        uses: ./.github/actions/setup
        with:
          python_version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: poetry install --with dev

      - name: Prepare environment
        run: make install-test

      - name: Run tests
        run: |
          export GLOCI_REGISTRY_TOKEN="invalid"
          make test-coverage-ci

      - name: Check for report
        run: test -f coverage.xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
