name: pre-release

on:
  push:
    tags: [ "[0-9]+.[0-9]+.[0-9]+*" ]

env:
  GIT_CLIFF_VERSION: 2.13.1

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # pin@v7.0.0
      - uses: gardenlinux/python-gardenlinux-lib/.github/actions/setup@main
      - run: make docs
      - if: ${{ github.ref_type != 'tag' }}
        name: Upload as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # pin@v7.0.1
        with:
          name: docs
          path: _build/
      - if: ${{ github.ref_type == 'tag' }}
        name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # pin@v4.1.0
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build
          force_orphan: true

  create-pre-release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Get the Git tag name
      id: get-tag-name
      run: echo "tag-name=${GITHUB_REF/refs\/tags\//}" | tee -a "$GITHUB_OUTPUT"
    - name: Checkout commit
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # pin@v7.0.0
      with:
        fetch-depth: 0
        ref: ${{ steps.get-tag-name.outputs.tag-name }}
    - uses: gardenlinux/python-gardenlinux-lib/.github/actions/setup@main
    - name: Use cargo cache
      id: cache-cargo
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo
        key: gh-release-${{ runner.os }}-git-cliff-${{ env.GIT_CLIFF_VERSION }}-
        restore-keys: gh-release-${{ runner.os }}-git-cliff-${{ env.GIT_CLIFF_VERSION }}-${{ hashFiles('~/.cargo/.crates.toml') }}-
    - name: Install git-cliff
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      run: |
        cargo install git-cliff@${GIT_CLIFF_VERSION}
    - id: release
      name: Create changelog and release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gl-gh-release create \
         --repo "python-gardenlinux-lib" \
         --tag "${{ steps.get-tag-name.outputs.tag-name }}" \
         --commit "${{ github.sha }}" \
         --name 'python-gardenlinux-lib v${{ steps.get-tag-name.outputs.tag-name }}' \
         --latest \
         --body "
         $(git-cliff -o - --current)
         "
